### ISSUE TITLE
Crash on resizing a tilled window too much

### ISSUE THREAD

**Issue by Pebor** [MarcusGrass/pgwm#1]
How to reproduce:
Spawn three tilled terminals, hold super and scroll to make the top right window smaller, keep scrolling until its consumed by the window bellow, keep scrolling on the overlapped window, welcome to your login screen.

I will now take this opportunity to say, that this project looks really cool :)

I also have two questions if I could, or this one is more of a suggestion:
Maybe a Makefile would be quite useful. And with even an install option right in there, a .desktop could be placed to `/usr/share/xsessions` for more accessibility
And as for the question, what is your stance on a reloadable config file? :thinking:

**Comment by MarcusGrass** [comment]
Thank you, thanks for trying it out!

Interesting, for me it created an extremely big window when resizing past zero, I'm guessing that you're running the release profile since that has debug assertions on, while optimized doesn't cause a crash but wraps instead. Fixed in this commit https://github.com/MarcusGrass/pgwm/commit/0f69426bbdd6939bdd72604a734dd64b42af4dbc .

I'll look into creating a makefile, If more people wants to use it it would be nice to be able to easily package it and a makefile would be a good start.

For reloadable config that's pretty much how I'm running it and it can be done with more or less ugly hacks. Ideally the application would support it, but reloading application state is [really messy](https://github.com/MarcusGrass/pgwm/blob/main/pgwm/src/x11/state_lifecycle.rs) It isn't impossible though and since that's basically what happens when you configure new monitors through xrandr it may not be that hard to implement since most of that stuff is in place anyways.
A more hackish way is doing this:
In ~/.xinitrc
```bash
while type pgwm ; do pgwm && continue || break ; done
```
If the application exits 0 it'll just relaunch, re-reading the config, the application exits 0 when using quit (default `mod+shift+q`) so quit is now a reload. 
If you actually want to close it down you'd now need to get it to crash or kill it, so you could bind something like this:
```toml
[[key-mapping]]
mods = ["M4", "Control"]
key = 0x0063 # q
on_click = { action = "Spawn", args = ["bash", ["-c", "killall pgwm"]] }
```

**Comment by Pebor** [comment]
The patch worked. Thanks!
Btw, when using shortcuts, I see that the user input is not taken away (when super + scrolling on a window) which is quite annoying at times, rip terminal output.

I also encountered a "bug"  I think? When creating more than 16 (on my pc at least, 1920x1080 monitor) windows on a single monitor/workspace, the wm, again, crashes. (I feel weird creating an another issue)

Would be cool if you figured something out with the reloads! But also with the wm being so light and fast to start, I don't see it as a real problem. The hacky way works just fine.

Also if anyone is later reading this and is using pgwm as a xsession selected from a login manager, adding
```
if [ "$DESKTOP_SESSION" = "pgwm" ]; then
    while type pgwm ; do pgwm && continue || break ; done
fi
```
should do the trick?

**Comment by MarcusGrass** [comment]
> The patch worked. Thanks!
> Btw, when using shortcuts, I see that the user input is not taken away (when super + scrolling on a window) which is quite annoying at times, rip terminal output.

Oo this is good, I took a shortcut when implementing key-grabbing, it seems that events are still propagated to the grab window, I hadn't noticed that myself so I just forgot about it, it seems fairly straight forward to actually grab the keys/buttons and not propagate it with a medium risk of introducing bugs, I'm checking that out!


> I also encountered a "bug" I think? When creating more than 16 (on my pc at least, 1920x1080 monitor) windows on a single monitor/workspace, the wm, again, crashes. (I feel weird creating an another issue)

That is feature-ish, I used heapless datastructures liberally previously but then I backed off on those and only kept them in "performance critical" sections where I could actually benchmark a noticable difference, the one we're talking about is the [workspace window limit](https://github.com/MarcusGrass/pgwm/blob/main/pgwm-core/src/config/mod.rs#L65). Its fairly easy to just rip out and avoid that but I'm a bit hesitant to do it since it'd slow down tiling calculations.


> Would be cool if you figured something out with the reloads! But also with the wm being so light and fast to start, I don't see it as a real problem. The hacky way works just fine.

I'll have another look into how easy it'd be to hot reload the configuration, I think I'll prioritize the button capture highest though

**Comment by Pebor** [comment]
Why not just disable spawning new windows when that level is reached? (which probably can cause problems when a sub window appears?)
I just saw that it's mentioned in the README, makes me wonder more why would it crash and not do something else when it's in the same paragraph as an explanation why errors crash and should be fixed if found :thinking:

**Comment by MarcusGrass** [comment]
> Why not just disable spawning new windows when that level is reached? (which probably can cause problems when a sub window appears?)

It's a bit complicated, windows can be spawned without explicit spawning, and spawning can be used without creating new windows, in the case of running some binary just performing background work with your spawn. 
The real problem is that you could have some Window which on some click spawns another window, think something like a popup. In that case there is no universal solution how to handle already having N windows spawned, one alternative would be to just have it be unmanaged but that would create some strange behaviour, most likely causing that window to just go missing at some point, never to be seen again. I instead chose to crash it, set the default to something I thought was high, it used to be 8, and then made a note of where to configure that if necessary. I think it's congruent with the statement that a crash is a bug or misconfiguration as if you'd like more than 16 windows you can just configure it to be some arbitrary number that you'd like.

The real choice here is whether or not to still keep this on the stack or not, if I didn't then you could have as many windows as you'd like, the priority is between being able to have infinite windows on a workspace without having to recompile with slightly slower tiling, or having some limit with slightly faster tiling. Since I generally don't have that many windows in a workspace i chose the latter, but getting feedback on usage patterns is great, do you generally have 16+ windows on a workspace, and in that case, what's usually your highest number? There may be some better way to communicate or mitigate this particular limit that I'm missing too, do you have any suggestions?

**Comment by Pebor** [comment]
I see. Great explanation, thank you!
Am all for performance.
And I don't actually use more than say 5 windows at a time, reason for me reaching that number was simply testing in my case.
16 I think is pretty reasonable, though this kind of information should be communicated to the user pretty early on, as I don't think everyone reads READMEs all the way to the end word by word.
Something like a "warning" section near the start, that there is a hardcoded maximum of 16 windows per workspace could save a few bug reports down the line.

**Comment by MarcusGrass** [comment]
@Pebor Hot reloading is now present, it was extremely easy it turned out, sorry it took so long, gonna launch 0.2 soon. It'll be pure safe Rust ripping out some c-libs!

**Comment by MarcusGrass** [comment]
For posterity, I checked into alacritty, which uses glutin, which uses winit, which listens to Raw-events. [Since xinput2](https://www.x.org/releases/X11R7.7/doc/inputproto/XI2proto.txt) these events are always sent, regardless of grab-state. This problem is present in all applications using winit and can only be fixed if winit changes their implementation to use regular xproto KeyPressEvents or regular xinput KeyPressEvents. I'm guessing that they're using that specific one for some reason, however I don't know what that reason may be.
